Repository Xilinx/XRT, pull requests merged in 2021-09, with the labels that each got.

#5608 CR-1105379 enforce --legacy for "all" old generation xbutil/xbmgmt subcommands
  src/runtime_src/core/tools/xbmgmt2/xbmgmt
  src/runtime_src/core/tools/xbutil2/xbutil
Labels: do not merge

#5779 Show reserved HOST MEM in legacy xbutil query
  src/runtime_src/core/common/info_platform.cpp
  src/runtime_src/core/common/query_requests.h
  src/runtime_src/core/pcie/driver/linux/xocl/userpf/xocl_sysfs.c
  src/runtime_src/core/pcie/linux/device_linux.cpp
  src/runtime_src/core/pcie/tools/xbutil/xbutil.h
  src/runtime_src/core/tools/common/ReportPcieInfo.cpp
Labels: 2021.2 review required

#5769 CR-1105737 : Enhanced the xbutil2 for AIE
  src/runtime_src/core/tools/common/ReportAie.cpp
  src/runtime_src/core/tools/common/ReportAieShim.cpp
Labels: 2021.2 review required

#5817 CR-1111237 Verify kernel Test Status : [PASSED] even though it FAILED
  src/runtime_src/core/tools/xbutil2/SubCmdValidate.cpp
Labels: 2021.2 approved

#5789 Fixed the issue for Ubuntu OS
  src/runtime_src/core/pcie/linux/scan.cpp
Labels: 2021.1

#5819 CR-1111672 start aie profile ctrs after group config
  src/runtime_src/xdp/profile/plugin/aie_profile/aie_plugin.cpp
Labels: 2021.2 approved

#5820 CR-1111660 ASTeR TC 17.12 - u55c/n + X3 - when an xclbin program is interrupted the server crashes
  src/runtime_src/core/common/drv/kds_core.c
Labels: 2021.2 review required

#5818 CR-1100087 - Change in the u30flashall.sh script to improve user experience
  src/runtime_src/core/tools/CMakeLists.txt
  src/runtime_src/core/tools/common/xball
Labels: 2021.1

#5790 CR-1110414, CR-1110307 and CR-1081361
  src/runtime_src/core/common/ishim.h
  src/runtime_src/core/pcie/tools/xbutil/xbutil.cpp
  src/runtime_src/core/tools/xbutil2/OO_HostMem.cpp
  src/runtime_src/core/tools/xbutil2/SubCmdValidate.cpp
  tests/validate/xcl_iops_test/src/xcl_api_iops.cpp
Labels: 2021.2 approved

#5822 CR-1111608: Fixing dfx issues on VCK190 DFx platform
  src/runtime_src/core/edge/drm/zocl/zocl_aie.c
  src/runtime_src/core/edge/drm/zocl/zocl_xclbin.c
  src/runtime_src/core/edge/user/aie/graph.cpp
Labels: 2021.2 approved

#5826 CR-1111784 Add xrt_coreutil to xrt.pc (#5784)
  src/CMake/config/xrt.pc.in
Labels: 2021.1

#5825 Update xrtdeps
  src/runtime_src/tools/scripts/xrtdeps.sh
Labels: 2021.2 approved

#5760 cherry-pick 3 PRs with manual conflict resolve
  src/runtime_src/core/common/query_requests.h
  src/runtime_src/core/pcie/driver/linux/xocl/mgmtpf/mgmt-core.c
  src/runtime_src/core/pcie/driver/linux/xocl/mgmtpf/mgmt-core.h
  src/runtime_src/core/pcie/driver/linux/xocl/mgmtpf/mgmt-sysfs.c
  src/runtime_src/core/pcie/driver/linux/xocl/mgmtpf/mgmt-utils.c
  src/runtime_src/core/pcie/driver/linux/xocl/subdev/icap.c
  src/runtime_src/core/pcie/driver/linux/xocl/subdev/intc.c
  src/runtime_src/core/pcie/driver/linux/xocl/subdev/mailbox.c
  src/runtime_src/core/pcie/driver/linux/xocl/xocl_drv.h
  src/runtime_src/core/pcie/driver/linux/xocl/xocl_fdt.c
  src/runtime_src/core/pcie/driver/linux/xocl/xocl_subdev.c
  src/runtime_src/core/pcie/driver/linux/xocl/xocl_xclbin.c
  src/runtime_src/core/pcie/linux/device_linux.cpp
  src/runtime_src/core/tools/xbmgmt2/OO_LoadConfig.cpp
  src/runtime_src/core/tools/xbmgmt2/SubCmdDump.cpp
Labels: 2021.1

#5850 Hal-level profiling callback mechanism refactoring
  src/runtime_src/core/common/api/native_profile.h
  src/runtime_src/core/edge/user/plugin/xdp/hal_profile.cpp
  src/runtime_src/core/edge/user/plugin/xdp/hal_profile.h
  src/runtime_src/core/edge/user/shim.cpp
  src/runtime_src/core/include/xclperf.h
  src/runtime_src/core/pcie/linux/plugin/xdp/hal_profile.cpp
  src/runtime_src/core/pcie/linux/plugin/xdp/hal_profile.h
  src/runtime_src/core/pcie/linux/shim.cpp
  src/runtime_src/xdp/profile/plugin/hal/xdp_hal_plugin.cpp
  src/runtime_src/xdp/profile/plugin/hal/xdp_hal_plugin_interface.h
Labels: 2022.1

#5762 Break up aie profile setmetrics function
  src/runtime_src/xdp/profile/plugin/aie_profile/aie_plugin.cpp
  src/runtime_src/xdp/profile/plugin/aie_profile/aie_plugin.h
  src/runtime_src/xdp/profile/plugin/aie_trace/aie_trace_plugin.cpp
  src/runtime_src/xdp/profile/plugin/aie_trace/aie_trace_plugin.h
Labels: 2022.1

#5803 Updated cmake build flow for ps kernel support
  build/debian/control
  src/CMake/Findlibdw.cmake
  src/CMake/Findlibelf.cmake
  src/CMake/Findlibffi.cmake
  src/runtime_src/core/common/CMakeLists.txt
  src/runtime_src/core/edge/skd/CMakeLists.txt
  src/runtime_src/tools/scripts/xrtdeps.sh
Labels: 2022.1
